## 1 GemStone Prediction ##

## 2 Order of the Project ##

   Understanding the problem

   Cleaning the dataest

   Training the Model

   Choosing the Best Model

   Predict the cost of Gemstone

## 3 Importing the Data and Packages ##

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
%matplotlib inline
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('gemstone.csv')

## 4 Cleaning the Data ##

In [3]:
df.head()

   id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [4]:
df.isnull().sum()

id         0
carat      0
cut        0
color      0
clarity    0
depth      0
table      0
x          0
y          0
z          0
price      0
dtype: int64

In [5]:
df.nunique()

id         193573
carat         248
cut             5
color           7
clarity         8
depth         153
table         108
x             522
y             521
z             349
price        8738
dtype: int64

In [6]:
df['cut'].unique()

array(['Premium', 'Very Good', 'Ideal', 'Good', 'Fair'], dtype=object)

In [7]:
df['carat'].unique()

array([1.52, 2.03, 0.7 , 0.32, 1.7 , 1.51, 0.74, 1.34, 0.3 , 1.01, 0.23,
       0.31, 0.33, 1.06, 0.26, 0.73, 0.39, 0.25, 0.4 , 0.71, 0.5 , 1.11,
       0.37, 0.38, 0.9 , 0.35, 0.41, 0.57, 1.5 , 1.  , 0.42, 1.04, 0.43,
       1.2 , 0.77, 0.52, 0.85, 1.44, 1.22, 0.75, 1.29, 1.02, 2.02, 1.54,
       2.01, 1.48, 0.59, 0.27, 1.61, 1.53, 1.25, 1.07, 2.  , 0.86, 0.55,
       0.97, 0.72, 1.21, 1.05, 0.91, 2.22, 1.27, 1.33, 1.08, 0.28, 0.56,
       0.58, 1.28, 1.36, 1.13, 2.1 , 0.34, 0.82, 2.32, 2.24, 1.67, 1.16,
       1.31, 2.18, 0.76, 1.19, 1.56, 1.74, 2.43, 1.09, 0.51, 0.95, 2.2 ,
       0.36, 0.68, 1.1 , 1.3 , 2.25, 2.04, 0.29, 0.94, 1.4 , 1.03, 1.26,
       1.65, 0.54, 1.12, 0.24, 1.17, 1.14, 0.61, 1.32, 1.82, 1.55, 1.24,
       0.96, 0.8 , 0.65, 2.14, 0.6 , 1.59, 1.18, 0.84, 0.79, 0.92, 0.53,
       2.05, 1.23, 1.6 , 0.46, 2.06, 0.62, 0.78, 0.83, 0.44, 2.08, 1.71,
       0.81, 2.09, 1.35, 1.73, 0.49, 2.11, 1.15, 2.21, 1.58, 0.47, 0.2 ,
       0.93, 2.31, 0.99, 1.62, 2.17, 0.98, 1.57, 2.33, 2.23, 0.45, 1.39,
       1.64, 0.21, 1.66, 1.47, 0.63, 0.69, 1.91, 2.28, 2.61, 2.44, 2.07,
       0.66, 2.34, 1.75, 2.12, 0.64, 2.26, 1.78, 1.8 , 1.63, 2.19, 1.68,
       1.72, 0.87, 2.13, 1.41, 2.5 , 2.38, 0.67, 1.76, 1.37, 1.83, 1.43,
       2.15, 1.93, 1.42, 2.42, 1.49, 2.29, 1.46, 3.01, 2.53, 1.84, 2.55,
       2.39, 1.69, 1.87, 2.41, 1.89, 0.48, 1.94, 2.16, 1.9 , 0.88, 3.  ,
       2.74, 2.51, 2.3 , 2.63, 2.54, 1.38, 2.52, 3.4 , 2.58, 1.77, 2.27,
       3.04, 2.36, 1.81, 0.89, 1.86, 1.79, 1.45, 0.22, 2.35, 2.66, 2.4 ,
       2.48, 2.57, 1.98, 2.56, 2.62, 2.37, 1.97, 2.49, 2.45, 1.88, 1.85,
       2.7 , 2.72, 1.95, 3.5 , 2.71, 1.96])

In [8]:
df['color'].unique()

array(['F', 'J', 'G', 'E', 'D', 'H', 'I'], dtype=object)

In [9]:
df['clarity'].unique()

array(['VS2', 'SI2', 'VS1', 'SI1', 'IF', 'VVS2', 'VVS1', 'I1'],
      dtype=object)

In [10]:
df.head()

   id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193573 entries, 0 to 193572
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   id       193573 non-null  int64
 1   carat    193573 non-null  float64
 2   cut      193573 non-null  object
 3   color    193573 non-null  object
 4   clarity  193573 non-null  object
 5   depth    193573 non-null  float64
 6   table    193573 non-null  float64
 7   x        193573 non-null  float64
 8   y        193573 non-null  float64
 9   z        193573 non-null  float64
 10  price    193573 non-null  int64
dtypes: float64(6), int64(2), object(3)
memory usage: 16.2+ MB

In [12]:
df.describe()

,id,carat,depth,table,x,y,z,price
count,193573.000000,193573.000000,193573.000000,193573.000000,193573.000000,193573.000000,193573.000000,193573.000000
mean,96786.000000,0.790688,61.820574,57.227675,5.715312,5.720094,3.534246,3969.155414
std,55879.856166,0.462688,1.081704,1.918844,1.109422,1.102333,0.688922,4034.374138
min,0.000000,0.200000,52.100000,49.000000,0.000000,0.000000,0.000000,326.000000
25%,48393.000000,0.400000,61.300000,56.000000,4.700000,4.710000,2.900000,951.000000
50%,96786.000000,0.700000,61.900000,57.000000,5.700000,5.720000,3.530000,2401.000000
75%,145179.000000,1.030000,62.400000,58.000000,6.510000,6.510000,4.030000,5408.000000
max,193572.000000,3.500000,71.600000,79.000000,9.650000,10.010000,31.300000,18818.000000

In [13]:
df.head()

   id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [14]:
X = df.drop('price',axis=1)
y=df['price']

In [15]:
X.head()

   id  carat        cut color clarity  depth  table     x     y     z
0   0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55
1   1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05
2   2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50
3   3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71
4   4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler , OneHotEncoder

num_features = X.select_dtypes(exclude=object).columns
cat_features = X.select_dtypes(include=object).columns

num_transformer = StandardScaler()
cat_transformer = OneHotEncoder()

processor = ColumnTransformer(
    [
        ("OneHotEncoder",num_transformer,num_features),
        ("StandardScaler",cat_transformer,cat_features)
    ]
)

X = processor.fit_transform(X)

In [17]:
X

array([[-1.73204186,  1.57625536,  0.35076759, ...,  1.        ,
         0.        ,  0.        ],
       [-1.73202396,  2.67851348,  0.16587371, ...,  0.        ,
         0.        ,  0.        ],
       [-1.73200607, -0.19600279, -0.57370182, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 1.73200607, -0.13116408,  1.18279005, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.73202396, -0.97406735,  0.99789617, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.73204186, -0.17438989, -0.94348958, ...,  0.        ,
         0.        ,  0.        ]], shape=(193573, 27))

In [18]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,-1.732042,1.576255,0.350768,0.402496,1.401353,1.460456,1.474414,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,-1.732024,2.678513,0.165874,0.402496,2.113437,2.177120,2.200187,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,-1.732006,-0.196003,-0.573702,-0.118652,-0.022816,0.008986,-0.049710,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,-1.731988,-1.017293,-0.203914,-0.639801,-1.203614,-1.188477,-1.196432,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,-1.731970,1.965288,0.720555,0.923644,1.743874,1.714463,1.793754,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193568,1.731970,-1.038906,-0.666149,-0.639801,-1.230655,-1.206620,-1.254494,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
193569,1.731988,-0.196003,-1.405724,0.402496,0.031267,0.045273,-0.093257,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
193570,1.732006,-0.131164,1.182790,-0.118652,0.004226,0.027129,0.124475,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
193571,1.732024,-0.974067,0.997896,-1.160949,-1.140517,-1.115903,-1.051277,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
193572,1.732042,-0.174390,-0.943490,3.529386,0.013239,-0.009157,-0.078741,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [19]:
y

0         13619
1         13387
2          2772
3           666
4         14453
          ...
193568     1130
193569     2874
193570     3036
193571      681
193572     2258
Name: price, Length: 193573, dtype: int64

In [20]:
X.shape

(193573, 27)

## 5 Training the model ##

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((154858, 27), (38715, 27), (154858,), (38715,))

In [22]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score
def evaluate_model(true,predicted):
    mae = mean_absolute_error(true,predicted)
    mse = mean_squared_error(true,predicted)
    rmse = root_mean_squared_error(true,predicted)
    r2_square = r2_score(true,predicted)

    return mae,mse,rmse,r2_square

In [23]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import AdaBoostRegressor,RandomForestRegressor,GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

In [ ]:
models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(),
    "Lasso": Lasso(),
    "ElasticNet":ElasticNet(),
    "DecisionTreeRegressor": DecisionTreeRegressor(),
    "AdaBoostRegressor": AdaBoostRegressor(),
    "KNeighborsRegressor": KNeighborsRegressor(),
    "RandomForestRegressor": RandomForestRegressor(),
    "GradientBoostingRegressor": GradientBoostingRegressor(),
    "XGBRegressor": XGBRegressor(),
    "CatBoostRegressor": CatBoostRegressor(),
}

In [25]:
model_list = []
r2_list = []


for name , model in models.items():
    model.fit(X_train,y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    train_mae,train_mse,train_rmse,train_r2_square = evaluate_model(y_train,y_train_pred)
    test_mae,test_mse,test_rmse,test_r2_square = evaluate_model(y_test,y_test_pred)

    print(name)
    model_list.append(name)

    print("For Training Data")
    print("Mean Absolute Error:", train_mae)
    print("Mean Squared Error:", train_mse)
    print("Root Mean Squared Error:", train_rmse)
    print("R2 Score:", train_r2_square)

    print("----------------------------------------------")

    print("For Test Data")
    print("Mean Absolute Error:", test_mae)
    print("Mean Squared Error:", test_mse)
    print("Root Mean Squared Error:", test_rmse)
    print("R2 Score:", test_r2_square)
    r2_list.append(test_r2_square)

    print("     ")

LinearRegression
For Training Data
Mean Absolute Error: 626.6974475424131
Mean Squared Error: 905712.0618395602
Root Mean Squared Error: 951.6890573288947
R2 Score: 0.9444524913754836
----------------------------------------------
For Test Data
Mean Absolute Error: 622.9514614402786
Mean Squared Error: 892385.1353007279
Root Mean Squared Error: 944.6613865829004
R2 Score: 0.9447766976776784

Ridge
For Training Data
Mean Absolute Error: 626.693109098429
Mean Squared Error: 905712.2921017312
Root Mean Squared Error: 951.6891783044142
R2 Score: 0.9444524772534568
----------------------------------------------
For Test Data
Mean Absolute Error: 622.9484551677818
Mean Squared Error: 892387.4936681949
Root Mean Squared Error: 944.6626348428283
R2 Score: 0.9447765517352658

Lasso
For Training Data
Mean Absolute Error: 624.6249759091369
Mean Squared Error: 906707.8358059884
Root Mean Squared Error: 952.2120750158488
R2 Score: 0.9443914203515691
----------------------------------------------
For Test Data
Mean Absolute Error: 620.9665371952511
Mean Squared Error: 893062.7672650516
Root Mean Squared Error: 945.0199824686522
R2 Score: 0.9447347639056456

ElasticNet
For Training Data
Mean Absolute Error: 1112.3561833030956
Mean Squared Error: 2572296.8914846387
Root Mean Squared Error: 1603.8381749679857
R2 Score: 0.84224049807358
----------------------------------------------
For Test Data
Mean Absolute Error: 1110.3094492739865
Mean Squared Error: 2561001.064747178
Root Mean Squared Error: 1600.3128021568714
R2 Score: 0.8415180503890161

DecisionTreeRegressor
For Training Data
Mean Absolute Error: 0.0
Mean Squared Error: 0.0
Root Mean Squared Error: 0.0
R2 Score: 1.0
----------------------------------------------
For Test Data
Mean Absolute Error: 426.36825519824356
Mean Squared Error: 702214.1628567738
Root Mean Squared Error: 837.9821972194718
R2 Score: 0.9565450123758644

AdaBoostRegressor
For Training Data
Mean Absolute Error: 983.6520957380114
Mean Squared Error: 1896494.6852021122
Root Mean Squared Error: 1377.1327768962992
R2 Score: 0.8836875875665714
----------------------------------------------
For Test Data
Mean Absolute Error: 982.0344040238007
Mean Squared Error: 1904696.4017320662
Root Mean Squared Error: 1380.1073877536003
R2 Score: 0.8821320290261873

KNeighborsRegressor
For Training Data
Mean Absolute Error: 315.5636066590037
Mean Squared Error: 350611.0161466633
Root Mean Squared Error: 592.1241560236023
R2 Score: 0.9784969536524654
----------------------------------------------
For Test Data
Mean Absolute Error: 383.86448146713155
Mean Squared Error: 529185.5318104095
Root Mean Squared Error: 727.4513948095841
R2 Score: 0.9672525107694485

RandomForestRegressor
For Training Data
Mean Absolute Error: 114.66630364592079
Mean Squared Error: 51072.611587507905
Root Mean Squared Error: 225.99250338785114
R2 Score: 0.9968677061373439
----------------------------------------------
For Test Data
Mean Absolute Error: 305.70810461061603
Mean Squared Error: 361595.3302000749
Root Mean Squared Error: 601.3279722415006
R2 Score: 0.977623463852018

GradientBoostingRegressor
For Training Data
Mean Absolute Error: 369.9225648923965
Mean Squared Error: 458763.65649174526
Root Mean Squared Error: 677.3209405383428
R2 Score: 0.9718639297859941
----------------------------------------------
For Test Data
Mean Absolute Error: 372.4546701171166
Mean Squared Error: 471749.2809563958
Root Mean Squared Error: 686.8400694167426
R2 Score: 0.9708068275321353

XGBRegressor
For Training Data
Mean Absolute Error: 279.6339416503906
Mean Squared Error: 265984.3125
Root Mean Squared Error: 515.7366943359375
R2 Score: 0.9836871027946472
----------------------------------------------
For Test Data
Mean Absolute Error: 302.0129699707031
Mean Squared Error: 350647.71875
Root Mean Squared Error: 592.1551513671875
R2 Score: 0.978300929069519

Learning rate set to 0.090822
0:	learn: 3707.8148112	total: 141ms	remaining: 2m 20s
1:	learn: 3412.1736489	total: 150ms	remaining: 1m 14s
2:	learn: 3140.8765341	total: 159ms	remaining: 52.9s
3:	learn: 2890.2608965	total: 168ms	remaining: 41.8s
4:	learn: 2670.5078004	total: 177ms	remaining: 35.2s
5:	learn: 2473.0098685	total: 186ms	remaining: 30.8s
6:	learn: 2292.2224174	total: 194ms	remaining: 27.5s
7:	learn: 2133.0070685	total: 203ms	remaining: 25.2s
8:	learn: 1984.0041034	total: 212ms	remaining: 23.3s
9:	learn: 1854.2353346	total: 222ms	remaining: 22s
10:	learn: 1734.5776282	total: 231ms	remaining: 20.7s
11:	learn: 1628.2682807	total: 240ms	remaining: 19.7s
12:	learn: 1537.3357311	total: 248ms	remaining: 18.8s
13:	learn: 1452.5751047	total: 257ms	remaining: 18.1s
14:	learn: 1376.4344618	total: 266ms	remaining: 17.5s
15:	learn: 1307.4255216	total: 275ms	remaining: 16.9s
16:	learn: 1249.0273046	total: 285ms	remaining: 16.5s
17:	learn: 1191.5309647	total: 292ms	remaining: 16s
18:	learn: 1141.5396742	total: 302ms	remaining: 15.6s
19:	learn: 1098.7698762	total: 311ms	remaining: 15.2s
20:	learn: 1056.7306114	total: 319ms	remaining: 14.9s
21:	learn: 1021.6266167	total: 327ms	remaining: 14.6s
22:	learn: 989.7953751	total: 336ms	remaining: 14.3s
23:	learn: 958.7604053	total: 345ms	remaining: 14s
24:	learn: 933.6200519	total: 353ms	remaining: 13.8s
25:	learn: 910.9474804	total: 362ms	remaining: 13.5s
26:	learn: 890.9122264	total: 370ms	remaining: 13.3s
27:	learn: 870.7445047	total: 379ms	remaining: 13.1s
28:	learn: 851.2263798	total: 388ms	remaining: 13s
29:	learn: 836.1497460	total: 399ms	remaining: 12.9s
30:	learn: 822.2300458	total: 407ms	remaining: 12.7s
31:	learn: 807.4355625	total: 418ms	remaining: 12.7s
32:	learn: 796.1138973	total: 430ms	remaining: 12.6s
33:	learn: 785.7815236	total: 439ms	remaining: 12.5s
34:	learn: 774.3838618	total: 453ms	remaining: 12.5s
35:	learn: 765.1156359	total: 463ms	remaining: 12.4s
36:	learn: 756.9929433	total: 472ms	remaining: 12.3s
37:	learn: 748.6588028	total: 482ms	remaining: 12.2s
38:	learn: 741.4366660	total: 493ms	remaining: 12.1s
39:	learn: 733.9926101	total: 501ms	remaining: 12s
40:	learn: 728.6009528	total: 511ms	remaining: 12s
41:	learn: 722.8780682	total: 521ms	remaining: 11.9s
42:	learn: 717.0587325	total: 530ms	remaining: 11.8s
43:	learn: 712.2577171	total: 542ms	remaining: 11.8s
44:	learn: 707.9683467	total: 550ms	remaining: 11.7s
45:	learn: 704.1976062	total: 559ms	remaining: 11.6s
46:	learn: 699.5164131	total: 567ms	remaining: 11.5s
47:	learn: 695.4934825	total: 579ms	remaining: 11.5s
48:	learn: 691.8329568	total: 588ms	remaining: 11.4s
49:	learn: 687.8525964	total: 597ms	remaining: 11.3s
50:	learn: 684.5576475	total: 605ms	remaining: 11.3s
51:	learn: 681.4613182	total: 614ms	remaining: 11.2s
52:	learn: 678.5101725	total: 624ms	remaining: 11.1s
53:	learn: 675.3682983	total: 631ms	remaining: 11.1s
54:	learn: 672.4749580	total: 642ms	remaining: 11s
55:	learn: 669.7517280	total: 653ms	remaining: 11s
56:	learn: 665.7879109	total: 662ms	remaining: 10.9s
57:	learn: 664.1744222	total: 670ms	remaining: 10.9s
58:	learn: 661.7621291	total: 678ms	remaining: 10.8s
59:	learn: 659.7345161	total: 687ms	remaining: 10.8s
60:	learn: 656.5121410	total: 696ms	remaining: 10.7s
61:	learn: 654.3237332	total: 705ms	remaining: 10.7s
62:	learn: 652.0593465	total: 712ms	remaining: 10.6s
63:	learn: 649.8354485	total: 722ms	remaining: 10.6s
64:	learn: 648.4066384	total: 729ms	remaining: 10.5s
65:	learn: 646.3202784	total: 739ms	remaining: 10.5s
66:	learn: 644.3525459	total: 747ms	remaining: 10.4s
67:	learn: 642.6432798	total: 759ms	remaining: 10.4s
68:	learn: 641.0619979	total: 768ms	remaining: 10.4s
69:	learn: 639.7752395	total: 777ms	remaining: 10.3s
70:	learn: 638.4093938	total: 787ms	remaining: 10.3s
71:	learn: 637.4240276	total: 796ms	remaining: 10.3s
72:	learn: 635.7622357	total: 805ms	remaining: 10.2s
73:	learn: 634.2412458	total: 815ms	remaining: 10.2s
74:	learn: 633.1309004	total: 824ms	remaining: 10.2s
75:	learn: 630.8947624	total: 834ms	remaining: 10.1s
76:	learn: 629.9554682	total: 842ms	remaining: 10.1s
77:	learn: 628.8919837	total: 856ms	remaining: 10.1s
78:	learn: 627.8862089	total: 865ms	remaining: 10.1s
79:	learn: 627.2477366	total: 874ms	remaining: 10s
80:	learn: 625.5555329	total: 886ms	remaining: 10.1s
81:	learn: 624.2874971	total: 899ms	remaining: 10.1s
82:	learn: 622.9935197	total: 909ms	remaining: 10s
83:	learn: 621.8230245	total: 920ms	remaining: 10s
84:	learn: 620.1319584	total: 931ms	remaining: 10s
85:	learn: 619.4864981	total: 941ms	remaining: 10s
86:	learn: 618.8490848	total: 954ms	remaining: 10s
87:	learn: 617.9679616	total: 972ms	remaining: 10.1s
88:	learn: 617.2829249	total: 997ms	remaining: 10.2s
89:	learn: 616.6673620	total: 1.01s	remaining: 10.3s
90:	learn: 615.8767817	total: 1.03s	remaining: 10.3s
91:	learn: 615.1669160	total: 1.05s	remaining: 10.4s
92:	learn: 614.4320353	total: 1.07s	remaining: 10.4s
93:	learn: 613.7573553	total: 1.09s	remaining: 10.5s
94:	learn: 613.2410025	total: 1.1s	remaining: 10.5s
95:	learn: 612.1815502	total: 1.12s	remaining: 10.5s
96:	learn: 611.8790639	total: 1.13s	remaining: 10.5s
97:	learn: 611.0256374	total: 1.15s	remaining: 10.6s
98:	learn: 610.6153309	total: 1.16s	remaining: 10.6s
99:	learn: 609.7070054	total: 1.18s	remaining: 10.6s
100:	learn: 609.3456243	total: 1.19s	remaining: 10.6s
101:	learn: 608.8221532	total: 1.21s	remaining: 10.6s
102:	learn: 608.3612705	total: 1.22s	remaining: 10.6s
103:	learn: 607.5993983	total: 1.24s	remaining: 10.7s
104:	learn: 607.1911295	total: 1.25s	remaining: 10.7s
105:	learn: 606.5472587	total: 1.27s	remaining: 10.7s
106:	learn: 606.1101069	total: 1.28s	remaining: 10.7s
107:	learn: 605.4669474	total: 1.29s	remaining: 10.7s
108:	learn: 604.9187888	total: 1.32s	remaining: 10.8s
109:	learn: 604.3549681	total: 1.34s	remaining: 10.8s
110:	learn: 604.0039112	total: 1.35s	remaining: 10.8s
111:	learn: 603.3783339	total: 1.37s	remaining: 10.9s
112:	learn: 603.0750097	total: 1.38s	remaining: 10.8s
113:	learn: 602.8101973	total: 1.4s	remaining: 10.8s
114:	learn: 602.4952000	total: 1.41s	remaining: 10.9s
115:	learn: 601.9346606	total: 1.43s	remaining: 10.9s
116:	learn: 601.6586467	total: 1.44s	remaining: 10.9s
117:	learn: 600.7922756	total: 1.46s	remaining: 10.9s
118:	learn: 600.0596190	total: 1.47s	remaining: 10.9s
119:	learn: 599.5492351	total: 1.49s	remaining: 10.9s
120:	learn: 599.1125050	total: 1.5s	remaining: 10.9s
121:	learn: 598.9292074	total: 1.51s	remaining: 10.9s
122:	learn: 598.5207472	total: 1.52s	remaining: 10.9s
123:	learn: 598.2926811	total: 1.54s	remaining: 10.9s
124:	learn: 597.7387459	total: 1.55s	remaining: 10.9s
125:	learn: 597.4080112	total: 1.57s	remaining: 10.9s
126:	learn: 596.5868003	total: 1.58s	remaining: 10.8s
127:	learn: 596.2945454	total: 1.59s	remaining: 10.8s
128:	learn: 595.6904046	total: 1.61s	remaining: 10.9s
129:	learn: 595.2608391	total: 1.62s	remaining: 10.9s
130:	learn: 595.0116561	total: 1.64s	remaining: 10.9s
131:	learn: 594.7272501	total: 1.66s	remaining: 10.9s
132:	learn: 594.1802916	total: 1.68s	remaining: 10.9s
133:	learn: 593.9463424	total: 1.7s	remaining: 11s
134:	learn: 593.6816056	total: 1.72s	remaining: 11s
135:	learn: 593.4412663	total: 1.74s	remaining: 11s
136:	learn: 592.9893715	total: 1.75s	remaining: 11s
137:	learn: 592.8060084	total: 1.77s	remaining: 11s
138:	learn: 592.4572703	total: 1.78s	remaining: 11.1s
139:	learn: 592.3208497	total: 1.8s	remaining: 11.1s
140:	learn: 592.0141433	total: 1.82s	remaining: 11.1s
141:	learn: 591.7598565	total: 1.84s	remaining: 11.1s
142:	learn: 591.5660368	total: 1.85s	remaining: 11.1s
143:	learn: 591.1029245	total: 1.87s	remaining: 11.1s
144:	learn: 590.9421490	total: 1.89s	remaining: 11.1s
145:	learn: 590.5760110	total: 1.9s	remaining: 11.1s
146:	learn: 590.4321512	total: 1.92s	remaining: 11.1s
147:	learn: 590.2339580	total: 1.93s	remaining: 11.1s
148:	learn: 589.9918140	total: 1.94s	remaining: 11.1s
149:	learn: 589.8479956	total: 1.95s	remaining: 11.1s
150:	learn: 589.5919609	total: 1.96s	remaining: 11s
151:	learn: 589.2325777	total: 1.97s	remaining: 11s
152:	learn: 589.0093593	total: 1.98s	remaining: 11s
153:	learn: 588.6719613	total: 2s	remaining: 11s
154:	learn: 588.5322431	total: 2s	remaining: 10.9s
155:	learn: 588.2871468	total: 2.01s	remaining: 10.9s
156:	learn: 588.0220213	total: 2.02s	remaining: 10.9s
157:	learn: 587.8582067	total: 2.03s	remaining: 10.8s
158:	learn: 587.6705505	total: 2.04s	remaining: 10.8s
159:	learn: 587.4427123	total: 2.05s	remaining: 10.8s
160:	learn: 587.2433415	total: 2.06s	remaining: 10.8s
161:	learn: 587.0778816	total: 2.07s	remaining: 10.7s
162:	learn: 586.8329695	total: 2.08s	remaining: 10.7s
163:	learn: 586.5523318	total: 2.09s	remaining: 10.7s
164:	learn: 586.2675334	total: 2.1s	remaining: 10.6s
165:	learn: 586.0810314	total: 2.11s	remaining: 10.6s
166:	learn: 585.9482533	total: 2.12s	remaining: 10.6s
167:	learn: 585.6917165	total: 2.13s	remaining: 10.5s
168:	learn: 585.4825309	total: 2.14s	remaining: 10.5s
169:	learn: 585.1398062	total: 2.15s	remaining: 10.5s
170:	learn: 584.8806548	total: 2.16s	remaining: 10.5s
171:	learn: 584.7509310	total: 2.17s	remaining: 10.4s
172:	learn: 584.6131290	total: 2.18s	remaining: 10.4s
173:	learn: 584.5235455	total: 2.19s	remaining: 10.4s
174:	learn: 584.3090831	total: 2.2s	remaining: 10.4s
175:	learn: 584.1636095	total: 2.21s	remaining: 10.3s
176:	learn: 583.9705109	total: 2.22s	remaining: 10.3s
177:	learn: 583.6525040	total: 2.22s	remaining: 10.3s
178:	learn: 583.3516655	total: 2.23s	remaining: 10.2s
179:	learn: 583.0990750	total: 2.24s	remaining: 10.2s
180:	learn: 582.7069870	total: 2.25s	remaining: 10.2s
181:	learn: 582.5490712	total: 2.26s	remaining: 10.2s
182:	learn: 582.4056591	total: 2.27s	remaining: 10.1s
183:	learn: 582.2637904	total: 2.28s	remaining: 10.1s
184:	learn: 582.1529375	total: 2.29s	remaining: 10.1s
185:	learn: 581.9108260	total: 2.3s	remaining: 10.1s
186:	learn: 581.7155350	total: 2.31s	remaining: 10s
187:	learn: 581.6140364	total: 2.32s	remaining: 10s
188:	learn: 581.4702571	total: 2.32s	remaining: 9.97s
189:	learn: 581.3504538	total: 2.33s	remaining: 9.95s
190:	learn: 581.1787691	total: 2.34s	remaining: 9.92s
191:	learn: 580.9825574	total: 2.35s	remaining: 9.89s
192:	learn: 580.8715775	total: 2.36s	remaining: 9.86s
193:	learn: 580.7250718	total: 2.37s	remaining: 9.84s
194:	learn: 580.5701142	total: 2.38s	remaining: 9.82s
195:	learn: 580.4599733	total: 2.39s	remaining: 9.79s
196:	learn: 580.3389847	total: 2.4s	remaining: 9.76s
197:	learn: 580.1422484	total: 2.41s	remaining: 9.75s
198:	learn: 580.0096455	total: 2.42s	remaining: 9.73s
199:	learn: 579.7855510	total: 2.42s	remaining: 9.7s
200:	learn: 579.5437082	total: 2.43s	remaining: 9.68s
201:	learn: 579.3761155	total: 2.44s	remaining: 9.66s
202:	learn: 579.3198796	total: 2.45s	remaining: 9.63s
203:	learn: 579.1064160	total: 2.46s	remaining: 9.61s
204:	learn: 578.8824154	total: 2.47s	remaining: 9.58s
205:	learn: 578.7192388	total: 2.48s	remaining: 9.56s
206:	learn: 578.5522113	total: 2.49s	remaining: 9.54s
207:	learn: 578.4695529	total: 2.5s	remaining: 9.52s
208:	learn: 578.3224602	total: 2.51s	remaining: 9.5s
209:	learn: 578.0374102	total: 2.52s	remaining: 9.47s
210:	learn: 577.8607876	total: 2.53s	remaining: 9.46s
211:	learn: 577.7805641	total: 2.54s	remaining: 9.43s
212:	learn: 577.6931275	total: 2.55s	remaining: 9.41s
213:	learn: 577.5689598	total: 2.55s	remaining: 9.38s
214:	learn: 577.5161724	total: 2.56s	remaining: 9.36s
215:	learn: 577.3054857	total: 2.57s	remaining: 9.35s
216:	learn: 577.1530197	total: 2.58s	remaining: 9.32s
217:	learn: 577.0726993	total: 2.59s	remaining: 9.3s
218:	learn: 576.9382448	total: 2.6s	remaining: 9.28s
219:	learn: 576.9000582	total: 2.61s	remaining: 9.26s
220:	learn: 576.7848594	total: 2.62s	remaining: 9.23s
221:	learn: 576.6888906	total: 2.63s	remaining: 9.21s
222:	learn: 576.5263480	total: 2.64s	remaining: 9.2s
223:	learn: 576.3050010	total: 2.65s	remaining: 9.17s
224:	learn: 576.2134118	total: 2.66s	remaining: 9.16s
225:	learn: 576.1309285	total: 2.67s	remaining: 9.14s
226:	learn: 576.0090717	total: 2.68s	remaining: 9.12s
227:	learn: 575.8901731	total: 2.69s	remaining: 9.1s
228:	learn: 575.8110173	total: 2.7s	remaining: 9.08s
229:	learn: 575.7090613	total: 2.71s	remaining: 9.06s
230:	learn: 575.6471685	total: 2.72s	remaining: 9.05s
231:	learn: 575.6112552	total: 2.73s	remaining: 9.03s
232:	learn: 575.5387278	total: 2.74s	remaining: 9.01s
233:	learn: 575.4290502	total: 2.75s	remaining: 8.99s
234:	learn: 575.2806237	total: 2.76s	remaining: 8.98s
235:	learn: 575.1101726	total: 2.77s	remaining: 8.96s
236:	learn: 574.9314860	total: 2.78s	remaining: 8.94s
237:	learn: 574.6985522	total: 2.79s	remaining: 8.93s
238:	learn: 574.5570527	total: 2.8s	remaining: 8.91s
239:	learn: 574.4774549	total: 2.81s	remaining: 8.9s
240:	learn: 574.3339742	total: 2.82s	remaining: 8.89s
241:	learn: 574.2487857	total: 2.83s	remaining: 8.87s
242:	learn: 573.9621471	total: 2.84s	remaining: 8.85s
243:	learn: 573.7828743	total: 2.85s	remaining: 8.83s
244:	learn: 573.6066108	total: 2.87s	remaining: 8.83s
245:	learn: 573.4564912	total: 2.88s	remaining: 8.83s
246:	learn: 573.3520771	total: 2.89s	remaining: 8.81s
247:	learn: 573.2761582	total: 2.9s	remaining: 8.8s
248:	learn: 573.1163148	total: 2.91s	remaining: 8.78s
249:	learn: 572.9838401	total: 2.92s	remaining: 8.76s
250:	learn: 572.8400756	total: 2.93s	remaining: 8.75s
251:	learn: 572.7281835	total: 2.94s	remaining: 8.73s
252:	learn: 572.5966023	total: 2.95s	remaining: 8.71s
253:	learn: 572.4725952	total: 2.96s	remaining: 8.69s
254:	learn: 572.3624780	total: 2.97s	remaining: 8.68s
255:	learn: 572.2449760	total: 2.98s	remaining: 8.66s
256:	learn: 572.0843827	total: 2.99s	remaining: 8.64s
257:	learn: 572.0642350	total: 3s	remaining: 8.62s
258:	learn: 572.0175266	total: 3.01s	remaining: 8.6s
259:	learn: 571.8805825	total: 3.02s	remaining: 8.59s
260:	learn: 571.7972727	total: 3.03s	remaining: 8.57s
261:	learn: 571.7375159	total: 3.04s	remaining: 8.56s
262:	learn: 571.6409234	total: 3.05s	remaining: 8.55s
263:	learn: 571.4692676	total: 3.06s	remaining: 8.55s
264:	learn: 571.3936425	total: 3.08s	remaining: 8.55s
265:	learn: 571.3166306	total: 3.11s	remaining: 8.6s
266:	learn: 571.2150459	total: 3.17s	remaining: 8.71s
267:	learn: 571.0943279	total: 3.2s	remaining: 8.74s
268:	learn: 570.9439785	total: 3.22s	remaining: 8.75s
269:	learn: 570.8587175	total: 3.23s	remaining: 8.74s
270:	learn: 570.7744047	total: 3.25s	remaining: 8.76s
271:	learn: 570.6493346	total: 3.27s	remaining: 8.74s
272:	learn: 570.5854086	total: 3.28s	remaining: 8.73s
273:	learn: 570.4343116	total: 3.29s	remaining: 8.73s
274:	learn: 570.3252454	total: 3.31s	remaining: 8.71s
275:	learn: 570.1993866	total: 3.32s	remaining: 8.71s
276:	learn: 570.1300940	total: 3.33s	remaining: 8.7s
277:	learn: 569.9752875	total: 3.35s	remaining: 8.69s
278:	learn: 569.8753414	total: 3.36s	remaining: 8.68s
279:	learn: 569.7846039	total: 3.37s	remaining: 8.66s
280:	learn: 569.7024109	total: 3.38s	remaining: 8.65s
281:	learn: 569.6688825	total: 3.39s	remaining: 8.64s
282:	learn: 569.5688967	total: 3.4s	remaining: 8.62s
283:	learn: 569.5100810	total: 3.42s	remaining: 8.61s
284:	learn: 569.4356736	total: 3.43s	remaining: 8.6s
285:	learn: 569.3667579	total: 3.44s	remaining: 8.59s
286:	learn: 569.2311873	total: 3.45s	remaining: 8.58s
287:	learn: 569.1723472	total: 3.47s	remaining: 8.57s
288:	learn: 569.0214831	total: 3.48s	remaining: 8.56s
289:	learn: 568.9216047	total: 3.49s	remaining: 8.55s
290:	learn: 568.8712119	total: 3.5s	remaining: 8.54s
291:	learn: 568.6821333	total: 3.52s	remaining: 8.52s
292:	learn: 568.6036820	total: 3.53s	remaining: 8.52s
293:	learn: 568.5098304	total: 3.55s	remaining: 8.52s
294:	learn: 568.3934117	total: 3.56s	remaining: 8.5s
295:	learn: 568.3231654	total: 3.57s	remaining: 8.49s
296:	learn: 568.3041290	total: 3.58s	remaining: 8.47s
297:	learn: 568.1950957	total: 3.59s	remaining: 8.46s
298:	learn: 568.1192045	total: 3.6s	remaining: 8.45s
299:	learn: 567.9768268	total: 3.61s	remaining: 8.43s
300:	learn: 567.8692818	total: 3.62s	remaining: 8.42s

In [26]:
pd.DataFrame(list(zip(model_list, r2_list)), columns=['Model Name', 'R2_Score']).sort_values(by=["R2_Score"],ascending=False)

                   Model Name  R2_Score
10          CatBoostRegressor  0.978977
9                XGBRegressor  0.978301
7       RandomForestRegressor  0.977623
8   GradientBoostingRegressor  0.970807
6         KNeighborsRegressor  0.967253
4       DecisionTreeRegressor  0.956545
0            LinearRegression  0.944777
1                       Ridge  0.944777
2                       Lasso  0.944735
5           AdaBoostRegressor  0.882132
3                  ElasticNet  0.841518